### ISSUE TITLE
Quiz 1

### ISSUE THREAD

**Issue by azmanyasin** [STIA1123-A202-Group-C/QUIZZES#1]
INSTRUCTION
Based on Exercise 2.4, use the Scanner class to get the input from the customer and use Setters and Getters method to retrieve the values.

SUBMISSION
Submit your coding before 9.15 am TODAY (14 April 2021).

**Comment by ThongWeiYong279932** [comment]
Name: Thong Wei Yong
Matric: 279932
https://github.com/ThongWeiYong279932/A202-STIA1123-C-Quiz-1.git

**Comment by ngcheesiang277275** [comment]
NG CHEE SIANG 277275
https://github.com/ngcheesiang277275/Quiz1

**Comment by Hazim280721** [comment]
https://github.com/Hazim280721/quiz-1.git

**Comment by yuvyyy** [comment]
Yuvanes raj(253888)
https://github.com/yuvyyy/quiz1.git

**Comment by Zulhasnan277834** [comment]
Mohammad Zulhasnan
277834
https://github.com/Zulhasnan277834/A202-STIA1123/tree/main/Quiz%201.0

**Comment by Hazim280721** [comment]
https://github.com/Hazim280721/quiz-1.git

**Comment by HazmanHaris278632** [comment]
https://github.com/HazmanHaris278632/Quiz-1.git

**Comment by qistinaliyana** [comment]
https://github.com/qistinaliyana/Quiz-1.git

**Comment by akmalzulkefle** [comment]
https://github.com/akmalzulkefle/Quiz1.git

**Comment by ooishikoon** [comment]
https://github.com/ooishikoon/A202-STIA-Programming-2/tree/main/Quiz%201

**Comment by OrnrakweeSuvanptum** [comment]
https://github.com/OrnrakweeSuvanptum/Quiz-1.git

**Comment by LidyiaNatasha** [comment]
https://github.com/LidyiaNatasha/NorAinLidyiaNatasha.git

**Comment by NurAzimahs** [comment]
Nur Azimah
https://github.com/NurAzimahs/Quiz-1.git

**Comment by IvanWongCheeKin11** [comment]
https://github.com/IvanWongCheeKin11/A202_STIA1123_C_Quiz1

**Comment by LidyiaNatasha** [comment]
https://github.com/LidyiaNatasha/NorAinLidyiaNatasha.git

**Comment by Pee278802** [comment]
NAME: PEE FOO YE
MATRIC NO: 278802
https://github.com/Pee278802/Quiz-1

**Comment by Dayat102** [comment]
Muhammad Hidayat Bin Ibrahim
279395
https://github.com/Dayat102/Quiz-1.git

**Comment by foomengtao280012** [comment]
https://github.com/foomengtao280012/Quiz-1.git

**Comment by zulhafizazmi** [comment]
https://github.com/zulhafizazmi/Quiz-1.git

**Comment by TanYeeJin-279890** [comment]
https://github.com/TanYeeJin-279890/A202-STIA1123-C--Exercise/tree/main/src

**Comment by nurFarhahdina** [comment]
https://github.com/dinanizam-280810/Quiz1.git

**Comment by Muhdsyarif** [comment]
https://github.com/Muhdsyarif/Exercise-2.4-quiz1

**Comment by NadzirahMokhtar** [comment]
https://github.com/NadzirahMokhtar/Quiz-1

**Comment by hws0406** [comment]
Ho Wee Sern 277538
https://github.com/hws0406/Quiz1.git

**Comment by HairulHaqimy** [comment]
https://github.com/HairulHaqimy/quiz.git

**Comment by Romadhan4** [comment]
https://github.com/Romadhan4/quiz1.git
